Repository recipyhq/recipy, pull requests merged in 2019-05, with the labels that each got.

#226 Feat/navbar notebook
  app/controllers/api/notebooks_controller.rb
  app/views/shared/_navbar.html.erb
Labels: enhancement

#215 Shopping List : base & API OK
  app/controllers/api/recipes_controller.rb
  app/controllers/api/shopping_lists_controller.rb
  app/controllers/recipes_controller.rb
  app/controllers/shopping_lists_controller.rb
  app/helpers/shopping_lists_helper.rb
  app/models/ingredient.rb
  app/models/recipe.rb
  app/models/shopping_list.rb
  app/models/shopping_list_ingredient.rb
  app/models/user.rb
  app/views/recipes/show.html.erb
  app/views/shopping_lists/_form.html.erb
  app/views/shopping_lists/_shopping_list.json.jbuilder
  app/views/shopping_lists/edit.html.erb
  app/views/shopping_lists/index.html.erb
  app/views/shopping_lists/index.json.jbuilder
  app/views/shopping_lists/new.html.erb
  app/views/shopping_lists/show.html.erb
  app/views/shopping_lists/show.json.jbuilder
  config/routes.rb
  db/migrate/20190311211851_create_shopping_lists.rb
  db/migrate/20190311212148_shopping_list_ingredient.rb
  db/migrate/20190511161416_add_checked_to_shopping_list_ingredient.rb
  db/schema.rb
  package-lock.json
  spec/controllers/shopping_lists_controller_spec.rb
  spec/factories/shopping_lists.rb
  spec/helpers/shopping_lists_helper_spec.rb
  spec/models/shopping_list_spec.rb
  spec/requests/shopping_lists_spec.rb
  spec/routing/shopping_lists_routing_spec.rb
  spec/views/shopping_lists/edit.html.erb_spec.rb
  spec/views/shopping_lists/index.html.erb_spec.rb
  spec/views/shopping_lists/new.html.erb_spec.rb
  spec/views/shopping_lists/show.html.erb_spec.rb
  yarn.lock
Labels: enhancement

#228 Feat/cooking notebook api
  app/controllers/api/notebooks_controller.rb
  config/routes.rb
Labels: enhancement

#231 Erreurdeconnexion#207
  app/admin/users.rb
  app/assets/images/producer/aubergine.jpg
  app/assets/images/producer/carrottes.jpg
  app/assets/images/producer/pommedeterre.jpg
  app/assets/images/producer/producer_background.jpg
  app/assets/images/producer/raisin.jpg
  app/assets/images/producer/user.png
  app/assets/images/registration/registration-cover1.jpg
  app/assets/images/registration/registration-cover2.jpeg
  app/assets/images/registration/registration-cover3.jpeg
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/registrations.scss
  app/controllers/producer/home_controller.rb
  app/controllers/users/confirmations_controller.rb
  app/controllers/users/omniauth_callbacks_controller.rb
  app/controllers/users/passwords_controller.rb
  app/controllers/users/registrations_controller.rb
  app/controllers/users/sessions_controller.rb
  app/controllers/users/unlocks_controller.rb
  app/helpers/producer_helper.rb
  app/models/user.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/shared/_omniauth.erb
  app/views/point_of_sales/_index.html.erb
  app/views/point_of_sales/index.html.erb
  app/views/producer/home/index.html.erb
  app/views/producer/home/new.html.erb
  app/views/producer/home/show.html.erb
  app/views/shared/_navbar.html.erb
  app/views/users/registrations/edit.html.erb
  app/views/users/registrations/new.html.erb
  app/views/users/sessions/new.html.erb
  config/application.yml
  config/initializers/assets.rb
  config/initializers/devise.rb
  config/initializers/simple_form.rb
  config/locales/en.yml
  config/locales/fr.yml
  config/routes.rb
  db/migrate/20190329072259_add_first_name_to_users.rb
  db/migrate/20190329072328_add_last_name_to_users.rb
  db/migrate/20190511160801_add_newsletters_to_users.rb
  db/migrate/20190512103900_addis_producer_to_users.rb
  db/migrate/20190512170241_add_bio_to_users.rb
  db/schema.rb
  spec/controllers/recipes_controller_spec.rb
  spec/helpers/producer_helper_spec.rb
  spec/requests/point_of_sales_spec.rb
  spec/views/search/index.html.erb_spec.rb
Labels: enhancement

#230 feat: empty parameter
  Gemfile
  Gemfile.lock
  app/controllers/api/notebooks_controller.rb
  config/routes.rb
  db/migrate/20190312201947_create_point_of_sales.rb
  db/migrate/20190312202038_create_openning_hours.rb
  db/migrate/20190318194733_delete_type_pointofsale.rb
  db/migrate/20190319143117_change_day_openninghours.rb
  db/migrate/20190319144125_change_type_pointofsale.rb
  db/schema.rb
  spec/controllers/producer/home_controller_spec.rb
Labels: bug, enhancement

#232 fix: registration impossible due to newsletter malfunction
  app/controllers/api/notebooks_controller.rb
  app/views/users/registrations/new.html.erb
  config/routes.rb
Labels: bug

#234 fix: back path & new seed product
  app/controllers/point_of_sales_controller.rb
  app/views/point_of_sales/_index.html.erb
  app/views/point_of_sales/edit.html.erb
  app/views/point_of_sales/show.html.erb
  app/views/producer/home/new.html.erb
  app/views/products/new.html.erb
  db/seeds.rb
Labels: bug

#227 feat: add some recipes
  app/assets/images/recipes_examples/avocat_crevettes.jpg
  app/assets/images/recipes_examples/crepes.jpg
  app/assets/images/recipes_examples/guacamole.jpg
  app/assets/images/recipes_examples/mayonnaise.jpg
  app/assets/images/recipes_examples/melon_jambon.png
  app/assets/images/recipes_examples/mousse_chocolat.jpg
  app/assets/images/recipes_examples/palmier_basilic.jpg
  app/assets/images/recipes_examples/poulet_curry.jpg
  app/assets/images/recipes_examples/quiche_au_saumon.jpeg
  app/assets/images/recipes_examples/ratatouille.jpg
  app/assets/images/recipes_examples/salade_avocats.jpg
  app/assets/images/recipes_examples/salade_cesar.jpg
  app/assets/images/recipes_examples/salade_de_fruits.jpeg
  app/assets/images/recipes_examples/spaghetti_carbo.jpg
  app/assets/images/recipes_examples/steak_vegetal.jpg
  app/assets/images/recipes_examples/welsh.jpeg
  app/controllers/producer/home_controller.rb
  app/controllers/users/omniauth_callbacks_controller.rb
  app/controllers/users/registrations_controller.rb
  app/controllers/users/sessions_controller.rb
  config/initializers/devise.rb
  db/seeds.rb
  spec/controllers/recipes_controller_spec.rb
  spec/models/user_spec.rb
  spec/routing/shopping_lists_routing_spec.rb
Labels: enhancement

#239 Fix: add list recipe ingredient
  app/views/recipes/show.html.erb
Labels: bug, enhancement

#246 fix: view for delete & edit for each notebooks and removing a recipe …
  app/assets/stylesheets/application.scss
  app/controllers/notebooks_controller.rb
  app/views/notebooks/_form.html.erb
  app/views/notebooks/index.html.erb
  app/views/notebooks/show.html.erb
  config/locales/fr.yml
Labels: bug
