Repository recipyhq/recipy, pull requests merged in 2019-03, with the labels that each got.

#200 Feat/beta/landing
  app/assets/images/cover.jpg
  app/assets/images/landing/cooker.jpeg
  app/assets/images/landing/cutlery.png
  app/assets/images/landing/iphone.png
  app/assets/images/landing/logo.png
  app/assets/images/landing/producer.jpeg
  app/assets/images/landing/waste.png
  app/assets/stylesheets/landing_pages.scss
  app/controllers/landing_pages_controller.rb
  app/views/landing_pages/index.html.erb
  app/views/layouts/application.html.erb
  config/routes.rb
  spec/routing/recipes_routing_spec.rb
Labels: enhancement

#201 Fix/update recipe
  Gemfile
  app/admin/ingredients.rb
  app/admin/quantity_equivalencies.rb
  app/admin/quantity_types.rb
  app/admin/recipe_categories.rb
  app/admin/recipe_ingredients.rb
  app/admin/recipe_quantities.rb
  app/admin/recipes.rb
  app/assets/images/recipes_examples/jambon_beurre.jpeg
  app/assets/images/recipes_examples/tomates_farcies.jpg
  app/controllers/api/ingredients_controller.rb
  app/controllers/api/recipes_controller.rb
  app/controllers/api/search_controller.rb
  app/controllers/application_controller.rb
  app/controllers/landing_pages_controller.rb
  app/controllers/recipes_controller.rb
  app/controllers/search_controller.rb
  app/models/ingredient.rb
  app/models/quantity_equivalency.rb
  app/models/quantity_type.rb
  app/models/recipe.rb
  app/models/recipe_category.rb
  app/models/recipe_ingredient.rb
  app/models/recipe_quantity.rb
  app/models/related_quantity_equivalency.rb
  app/models/related_quantity_type.rb
  app/models/related_recipe_category.rb
  app/models/related_recipe_ingr_quant.rb
  app/models/related_recipe_quantity.rb
  app/views/recipes/_form.html.erb
  app/views/recipes/show.html.erb
  app/views/search/index.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  config/routes.rb
  db/migrate/20190203180708_create_recipe_categories.rb
  db/migrate/20190203181253_create_related_recipe_categories.rb
  db/migrate/20190203193559_create_quantity_type.rb
  db/migrate/20190210184348_create_quantity_equivalency.rb
  db/migrate/20190210190417_create_related_quantity_types.rb
  db/migrate/20190210221526_create_related_quantity_equivalencies.rb
  db/migrate/20190214184654_create_recipe_quantity.rb
  db/migrate/20190214190554_create_related_recipe_quantity.rb
  db/migrate/20190215195956_create_related_recipe_ingr_quant.rb
  db/migrate/20190216151333_add_recipe_quantity_association_to_recipe_ingredient.rb
  db/migrate/20190216153121_remove_quantity_from_recipe_ingredient.rb
  db/migrate/20190216161730_add_steps_to_recipe.rb
  db/migrate/20190216180642_rename_time_of_recipe.rb
  db/migrate/20190216184325_remove_time_from_recipe.rb
  db/schema.rb
  db/seeds.rb
  spec/views/recipes/new.html.erb_spec.rb
  spec/views/recipes/show.html.erb_spec.rb
Labels: priority

#206 fix: api - No quantity for ingredient
  app/admin/recipes.rb
  app/controllers/api/recipes_controller.rb
  db/seeds.rb
Labels: bug

#210 Update landing legal
  app/assets/stylesheets/landing_pages.scss
  app/assets/stylesheets/main.scss
  app/assets/stylesheets/styles/footer.scss
  app/controllers/landing_pages_controller.rb
  app/views/landing_pages/index.html.erb
  app/views/landing_pages/legal_notice.html.erb
  app/views/landing_pages/privacy_policy.html.erb
  app/views/landing_pages/shared/_footer.html.erb
  app/views/landing_pages/shared/_navbar.html.erb
  app/views/layouts/application.html.erb
  app/views/shared/_footer.html.erb
  config/routes.rb
Labels: enhancement

#212 Feat/recipes/user feedback
  app/assets/stylesheets/application.scss
  app/controllers/api/base_controller.rb
  app/controllers/api/ingredients_controller.rb
  app/controllers/api/recipes_controller.rb
  app/controllers/api/scores_controller.rb
  app/controllers/api/search_controller.rb
  app/controllers/application_controller.rb
  app/controllers/recipes_controller.rb
  app/controllers/scores_controller.rb
  app/controllers/search_controller.rb
  app/helpers/application_helper.rb
  app/helpers/recipes_helper.rb
  app/helpers/scores_helper.rb
  app/models/recipe.rb
  app/models/recipe_score.rb
  app/models/user.rb
  app/views/cook/home/index.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/recipes/show.html.erb
  app/views/shared/_navbar.html.erb
  config/locales/fr.yml
  config/routes.rb
  db/migrate/20190325010553_remove_notes_recipes.rb
  db/migrate/20190325013535_create_recipe_scores.rb
  db/migrate/20190326140527_add_content_recipe_scores.rb
  db/schema.rb
  spec/controllers/scores_controller_spec.rb
  spec/factories/recipe_scores.rb
  spec/helpers/scores_helper_spec.rb
  spec/models/recipe_score_spec.rb
Labels: enhancement
