Repository recipyhq/recipy, pull requests merged in 2019-06, with the labels that each got.

#259 fix: social network connection disabled
  app/views/users/registrations/new.html.erb
  app/views/users/sessions/new.html.erb
Labels: invalid

#260 fix: bad ux to access notebooks etc.
  app/views/shared/_navbar.html.erb
Labels: invalid

#258 Feat: Add /api/user?user_id=nbr
  app/controllers/api/user_controller.rb
  config/routes.rb
Labels: enhancement

#266 Feat/design
  .eslintrc.js
  app/assets/javascripts/application.js
  app/assets/javascripts/search.js
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/base/variables.scss
  app/controllers/api/search_controller.rb
  app/controllers/notebooks_controller.rb
  app/controllers/producer/home_controller.rb
  app/controllers/search_controller.rb
  app/views/ingredients/_form.html.erb
  app/views/notebooks/_form.html.erb
  app/views/notebooks/index.html.erb
  app/views/notebooks/show.html.erb
  app/views/producer/home/index.html.erb
  app/views/products/_form_new.html.erb
  app/views/recipes/_edit_form.html.erb
  app/views/recipes/_form.html.erb
  app/views/recipes/show.html.erb
  app/views/search/index.html.erb
  app/views/shared/_navbar.html.erb
  app/views/shopping_lists/_form.html.erb
  config/locales/fr.yml
Labels: enhancement

#253 Changes for ingredient fields
  Gemfile
  Gemfile.lock
  app/admin/ingredients.rb
  app/assets/javascripts/search.js
  app/assets/stylesheets/application.scss
  app/controllers/api/user_controller.rb
  app/controllers/notebooks_controller.rb
  app/controllers/point_of_sales_controller.rb
  app/controllers/recipes_controller.rb
  app/controllers/users/registrations_controller.rb
  app/models/ingredient.rb
  app/models/user.rb
  app/views/ingredients/_form.html.erb
  app/views/point_of_sales/_opening_hours_fields.html.erb
  app/views/recipes/_edit_form.html.erb
  app/views/recipes/_edit_recipe_ingredient_fields.html.erb
  app/views/recipes/_recipe_ingredient_fields.html.erb
  app/views/recipes/show.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  db/schema.rb
  package-lock.json
  yarn.lock
Labels: bug

#268 #243 Shopping list quantities
  app/controllers/api/recipes_controller.rb
  app/controllers/api/shopping_lists_controller.rb
  app/controllers/recipes_controller.rb
  app/controllers/shopping_lists_controller.rb
  app/models/quantity_type.rb
  app/models/r_shp_lst_ing_quantity.rb
  app/models/r_shp_lst_quantity.rb
  app/models/shopping_list_ingredient.rb
  app/models/shopping_list_quantity.rb
  app/views/recipes/show.html.erb
  app/views/shopping_lists/show.html.erb
  config/routes.rb
  db/migrate/20190531152553_create_shopping_list_quantity.rb
  db/migrate/20190531153028_create_related_shopping_list_quantity.rb
  db/migrate/20190531153122_create_related_shopping_list_ingr_quant.rb
  db/schema.rb
  package-lock.json
Labels: enhancement

#269 #243 Staging shopping list
  package-lock.json
Labels: enhancement

#275 Notebook | Problème de front
  .travis.yml
  Gemfile.lock
  app/controllers/meal_plans_controller.rb
  app/controllers/meals_controller.rb
  app/controllers/notebooks_controller.rb
  app/helpers/meal_plans_helper.rb
  app/helpers/meals_helper.rb
  app/models/meal.rb
  app/models/meal_plan.rb
  app/views/meal_plans/_form.html.erb
  app/views/meal_plans/_meal_plan.json.jbuilder
  app/views/meal_plans/edit.html.erb
  app/views/meal_plans/index.html.erb
  app/views/meal_plans/index.json.jbuilder
  app/views/meal_plans/new.html.erb
  app/views/meal_plans/show.html.erb
  app/views/meal_plans/show.json.jbuilder
  app/views/meals/_form.html.erb
  app/views/meals/_meal.json.jbuilder
  app/views/meals/edit.html.erb
  app/views/meals/index.html.erb
  app/views/meals/index.json.jbuilder
  app/views/meals/new.html.erb
  app/views/meals/show.html.erb
  app/views/meals/show.json.jbuilder
  app/views/notebooks/_form.html.erb
  app/views/notebooks/index.html.erb
  app/views/notebooks/show.html.erb
  config/routes.rb
  db/migrate/20190606195422_create_meals.rb
  db/migrate/20190606200051_create_meal_plans.rb
  db/schema.rb
  spec/controllers/meal_plans_controller_spec.rb
  spec/controllers/meals_controller_spec.rb
  spec/factories/meal_plans.rb
  spec/factories/meals.rb
  spec/helpers/meal_plans_helper_spec.rb
  spec/helpers/meals_helper_spec.rb
  spec/models/meal_plan_spec.rb
  spec/models/meal_spec.rb
  spec/requests/meal_plans_spec.rb
  spec/requests/meals_spec.rb
  spec/routing/meal_plans_routing_spec.rb
  spec/routing/meals_routing_spec.rb
Labels: bug

#267 Feat/like producer
  app/controllers/api/shopping_lists_controller.rb
  app/controllers/api/user_controller.rb
  app/controllers/producer/home_controller.rb
  app/controllers/recipes_controller.rb
  app/controllers/shopping_lists_controller.rb
  app/controllers/users/base_controller.rb
  app/controllers/users/registrations_controller.rb
  app/models/liked_producer.rb
  app/models/user.rb
  app/views/producer/home/show.html.erb
  app/views/shared/_navbar.html.erb
  app/views/users/base/show_liked_producers.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  config/routes.rb
  db/migrate/20190610133256_create_liked_producer.rb
  db/schema.rb
  spec/controllers/cook/home_controller_spec.rb
  spec/views/point_of_sales/edit.html.erb_spec.rb
  spec/views/point_of_sales/index.html.erb_spec.rb
  spec/views/point_of_sales/new.html.erb_spec.rb
  spec/views/point_of_sales/show.html.erb_spec.rb
  spec/views/products/edit.html.erb_spec.rb
Labels: enhancement
